#!/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby
require 'fileutils'
FileUtils.mkdir_p('/usr/local/var/mac-setup')

require 'net/http'
# Must be somedomain.net instead of somedomain.net/, otherwise, it will throw exception.
Net::HTTP.start("raw.githubusercontent.com", use_ssl: true) do |http|
  f = File.open('/usr/local/var/mac-setup/Brewfile', 'w')
  begin
    http.request_get('/eigilsagafos/mac-setup/master/Brewfile') do |resp|
      resp.read_body do |segment|
        f.write(segment)
      end
    end
  ensure
    f.close()
  end
end
puts "Done."
